trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
# Step 1: Maven Build and Test Execution
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean package'

# Step 2: Publish Unit Test Results
- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/target/surefire-reports/TEST-*.xml'
    mergeTestResults: true
    testRunTitle: 'Maven Unit Test Results'